### ISSUE TITLE
Serial UART or USB? /  Singal Level 3,3V or 5V

### ISSUE THREAD

**Issue by careyer** [lasitha-sparrow/Makeskyblue_wifi_Controller#2]
Please excuse my ignorant question but:
Does the MSB use Serial TX/RX or a USB Interface? (I don't get why the FTDI shows in the picture in the readme? Is that just for programming the ESP?)

If MSB uses Serial - is that 3,3V or 5V Signal level? (Any sort of 5V<->3,3V Level-Shifter needed)?

Thank you very much

**Comment by lasitha-sparrow** [comment]
MSB usb mini port is actually not a usb port but an ftdi port.and its 5v logic.so if you connecting esp8266 or esp32 you need a logic level shifter

**Comment by careyer** [comment]
Thank you sir!
